export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  // Access
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  // Timeclock
  SESSION_ALREADY_OPEN = 'SESSION_ALREADY_OPEN',
  NO_OPEN_SESSION = 'NO_OPEN_SESSION',
  // Breaks
  BREAK_ALREADY_OPEN = 'BREAK_ALREADY_OPEN',
  NO_OPEN_BREAK = 'NO_OPEN_BREAK',
  // Overtime
  OT_ALREADY_REVIEWED = 'OT_ALREADY_REVIEWED',
  // Users
  EMPLOYEE_ID_TAKEN = 'EMPLOYEE_ID_TAKEN',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  CANNOT_DEACTIVATE_SELF = 'CANNOT_DEACTIVATE_SELF',
  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
